# SITE SETTINGS
# replace with the name you want displayed on the bio (i.e. your name)
name: Michelle Mesquita
# replace with your desired description
description: Cybersecurity Girl, Brasil
# replace with keywords you want placed in the meta keywords section of the HTML header
keywords: Cybsersecurity, Pentest, Software Developer, Python
# replace with your contact email (used for the email link in the footer)
email: michelleamesquita@gmail.com
# replace with the production URL of your bio site
root_url: https://michelleamesquita.github.io
# optionally replace with the name / extension of your image file
# i.e if using perhaps a .jpg instead, the below should be changed to `profile.jpg`
profile_image_file: profile.png

# Icon Links to display in the navbar as round icon buttons
# options, leave empty and no extra buttons will appear in
# the navbar
navbar-links:
  - fa-icon: linkedin-in
    url: https://www.linkedin.com/in/michelleamesquita


# Icon Links to display in the footer, leave empty and
# just the email link will appear (which can be removed by
# updating /_includes/footer.html)
footer-links:
  - fa-icon: github
    url: https://github.com/michelleamesquita
  - fa-icon: stack-overflow
    url: https://www.stackoverflow.com/users/13297082

# Build settings
sass:
  sass_dir: css
